#!c:\python27\python.exe
# EASY-INSTALL-SCRIPT: 'jsbeautifier==1.5.10','js-beautify'
__requires__ = 'jsbeautifier==1.5.10'
__import__('pkg_resources').run_script('jsbeautifier==1.5.10', 'js-beautify')
