# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_bookmarksdialog.ui'
#
# Created: Tue Apr 21 13:54:42 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BookmarksDialog(object):
    def setupUi(self, BookmarksDialog):
        BookmarksDialog.setObjectName(_fromUtf8("BookmarksDialog"))
        BookmarksDialog.resize(587, 525)
        self.verticalLayout = QtGui.QVBoxLayout(BookmarksDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(BookmarksDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.bookmarks = QtGui.QWidget()
        self.bookmarks.setObjectName(_fromUtf8("bookmarks"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.bookmarks)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_5 = QtGui.QLabel(self.bookmarks)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.bookmarksList = QtGui.QListWidget(self.bookmarks)
        self.bookmarksList.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.bookmarksList.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.bookmarksList.setObjectName(_fromUtf8("bookmarksList"))
        self.verticalLayout_2.addWidget(self.bookmarksList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.addFromQgisButton = QtGui.QPushButton(self.bookmarks)
        self.addFromQgisButton.setMaximumSize(QtCore.QSize(1111111, 16777215))
        self.addFromQgisButton.setObjectName(_fromUtf8("addFromQgisButton"))
        self.verticalLayout_5.addWidget(self.addFromQgisButton)
        self.addFromLayerButton = QtGui.QPushButton(self.bookmarks)
        self.addFromLayerButton.setObjectName(_fromUtf8("addFromLayerButton"))
        self.verticalLayout_5.addWidget(self.addFromLayerButton)
        self.removeButton = QtGui.QPushButton(self.bookmarks)
        self.removeButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.verticalLayout_5.addWidget(self.removeButton)
        self.removeAllButton = QtGui.QPushButton(self.bookmarks)
        self.removeAllButton.setObjectName(_fromUtf8("removeAllButton"))
        self.verticalLayout_5.addWidget(self.removeAllButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.label_3 = QtGui.QLabel(self.bookmarks)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.descriptionBox = QtGui.QTextEdit(self.bookmarks)
        self.descriptionBox.setObjectName(_fromUtf8("descriptionBox"))
        self.verticalLayout_6.addWidget(self.descriptionBox)
        self.tabWidget.addTab(self.bookmarks, _fromUtf8(""))
        self.configuration = QtGui.QWidget()
        self.configuration.setObjectName(_fromUtf8("configuration"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.configuration)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.storyPanelGroup = QtGui.QGroupBox(self.configuration)
        self.storyPanelGroup.setCheckable(True)
        self.storyPanelGroup.setChecked(False)
        self.storyPanelGroup.setObjectName(_fromUtf8("storyPanelGroup"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.storyPanelGroup)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.storyPanelGroup)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.animationTypeCombo = QtGui.QComboBox(self.storyPanelGroup)
        self.animationTypeCombo.setMinimumSize(QtCore.QSize(200, 0))
        self.animationTypeCombo.setObjectName(_fromUtf8("animationTypeCombo"))
        self.animationTypeCombo.addItem(_fromUtf8(""))
        self.animationTypeCombo.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.animationTypeCombo)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.moveAutomaticallyCheck = QtGui.QCheckBox(self.storyPanelGroup)
        self.moveAutomaticallyCheck.setObjectName(_fromUtf8("moveAutomaticallyCheck"))
        self.horizontalLayout_3.addWidget(self.moveAutomaticallyCheck)
        self.transitionTimeBox = QtGui.QSpinBox(self.storyPanelGroup)
        self.transitionTimeBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.transitionTimeBox.setObjectName(_fromUtf8("transitionTimeBox"))
        self.horizontalLayout_3.addWidget(self.transitionTimeBox)
        self.label_2 = QtGui.QLabel(self.storyPanelGroup)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.showIndicatorsCheck = QtGui.QCheckBox(self.storyPanelGroup)
        self.showIndicatorsCheck.setObjectName(_fromUtf8("showIndicatorsCheck"))
        self.verticalLayout_3.addWidget(self.showIndicatorsCheck)
        self.label_4 = QtGui.QLabel(self.storyPanelGroup)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.introTitleBox = QtGui.QLineEdit(self.storyPanelGroup)
        self.introTitleBox.setObjectName(_fromUtf8("introTitleBox"))
        self.verticalLayout_3.addWidget(self.introTitleBox)
        self.label_6 = QtGui.QLabel(self.storyPanelGroup)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.introDescriptionBox = QtGui.QTextEdit(self.storyPanelGroup)
        self.introDescriptionBox.setObjectName(_fromUtf8("introDescriptionBox"))
        self.verticalLayout_3.addWidget(self.introDescriptionBox)
        self.verticalLayout_7.addWidget(self.storyPanelGroup)
        self.tabWidget.addTab(self.configuration, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(BookmarksDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(BookmarksDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BookmarksDialog)

    def retranslateUi(self, BookmarksDialog):
        BookmarksDialog.setWindowTitle(_translate("BookmarksDialog", "Bookmarks", None))
        self.label_5.setText(_translate("BookmarksDialog", "Bookmarks to use (drag to reorder, select to edit description)", None))
        self.addFromQgisButton.setText(_translate("BookmarksDialog", "Add from QGIS bookmarks...", None))
        self.addFromLayerButton.setText(_translate("BookmarksDialog", "Add from layer...", None))
        self.removeButton.setText(_translate("BookmarksDialog", "Remove", None))
        self.removeAllButton.setText(_translate("BookmarksDialog", "Remove all", None))
        self.label_3.setText(_translate("BookmarksDialog", "Bookmark description text", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bookmarks), _translate("BookmarksDialog", "Bookmarks", None))
        self.storyPanelGroup.setTitle(_translate("BookmarksDialog", "Show as story panel", None))
        self.label.setText(_translate("BookmarksDialog", "Animation type:", None))
        self.animationTypeCombo.setItemText(0, _translate("BookmarksDialog", "Go to", None))
        self.animationTypeCombo.setItemText(1, _translate("BookmarksDialog", "Pan to", None))
        self.moveAutomaticallyCheck.setText(_translate("BookmarksDialog", "Move automatically each", None))
        self.label_2.setText(_translate("BookmarksDialog", "seconds", None))
        self.showIndicatorsCheck.setText(_translate("BookmarksDialog", "Show indicators", None))
        self.label_4.setText(_translate("BookmarksDialog", "Intro title", None))
        self.label_6.setText(_translate("BookmarksDialog", "Intro description", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configuration), _translate("BookmarksDialog", "Configuration", None))

